/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionIndexRouteImport } from './routes/reception.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as ReceptionScheduleRouteImport } from './routes/reception.schedule'
import { Route as ReceptionRequestsRouteImport } from './routes/reception.requests'
import { Route as ReceptionRegisterRouteImport } from './routes/reception.register'
import { Route as ReceptionQueueRouteImport } from './routes/reception.queue'
import { Route as ReceptionProfileRouteImport } from './routes/reception.profile'
import { Route as ReceptionPatientsRouteImport } from './routes/reception.patients'
import { Route as ReceptionBillingRouteImport } from './routes/reception.billing'
import { Route as PatientRequestAppointmentRouteImport } from './routes/patient.request-appointment'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientMedicalRecordsRouteImport } from './routes/patient.medical-records'
import { Route as PatientLabReportsRouteImport } from './routes/patient.lab-reports'
import { Route as PatientBillingRouteImport } from './routes/patient.billing'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as LabUploadRouteImport } from './routes/lab.upload'
import { Route as LabSearchRouteImport } from './routes/lab.search'
import { Route as LabProfileRouteImport } from './routes/lab.profile'
import { Route as LabPendingRouteImport } from './routes/lab.pending'
import { Route as LabInProgressRouteImport } from './routes/lab.in-progress'
import { Route as LabCompletedRouteImport } from './routes/lab.completed'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorMedicalRecordsRouteImport } from './routes/doctor.medical-records'
import { Route as DoctorLabRequestsRouteImport } from './routes/doctor.lab-requests'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor.patients.$id'
import { Route as DoctorConsultationIdRouteImport } from './routes/doctor.consultation.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionIndexRoute = ReceptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceptionRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const ReceptionScheduleRoute = ReceptionScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionRequestsRoute = ReceptionRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionRegisterRoute = ReceptionRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionQueueRoute = ReceptionQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionProfileRoute = ReceptionProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionPatientsRoute = ReceptionPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionBillingRoute = ReceptionBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ReceptionRoute,
} as any)
const PatientRequestAppointmentRoute =
  PatientRequestAppointmentRouteImport.update({
    id: '/request-appointment',
    path: '/request-appointment',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicalRecordsRoute = PatientMedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLabReportsRoute = PatientLabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBillingRoute = PatientBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const LabUploadRoute = LabUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LabRoute,
} as any)
const LabSearchRoute = LabSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LabRoute,
} as any)
const LabProfileRoute = LabProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LabRoute,
} as any)
const LabPendingRoute = LabPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => LabRoute,
} as any)
const LabInProgressRoute = LabInProgressRouteImport.update({
  id: '/in-progress',
  path: '/in-progress',
  getParentRoute: () => LabRoute,
} as any)
const LabCompletedRoute = LabCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => LabRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorMedicalRecordsRoute = DoctorMedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorLabRequestsRoute = DoctorLabRequestsRouteImport.update({
  id: '/lab-requests',
  path: '/lab-requests',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorPatientsRoute,
} as any)
const DoctorConsultationIdRoute = DoctorConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/reception': typeof ReceptionRouteWithChildren
  '/register': typeof RegisterRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/lab-requests': typeof DoctorLabRequestsRoute
  '/doctor/medical-records': typeof DoctorMedicalRecordsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/lab/completed': typeof LabCompletedRoute
  '/lab/in-progress': typeof LabInProgressRoute
  '/lab/pending': typeof LabPendingRoute
  '/lab/profile': typeof LabProfileRoute
  '/lab/search': typeof LabSearchRoute
  '/lab/upload': typeof LabUploadRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/lab-reports': typeof PatientLabReportsRoute
  '/patient/medical-records': typeof PatientMedicalRecordsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/request-appointment': typeof PatientRequestAppointmentRoute
  '/reception/billing': typeof ReceptionBillingRoute
  '/reception/patients': typeof ReceptionPatientsRoute
  '/reception/profile': typeof ReceptionProfileRoute
  '/reception/queue': typeof ReceptionQueueRoute
  '/reception/register': typeof ReceptionRegisterRoute
  '/reception/requests': typeof ReceptionRequestsRoute
  '/reception/schedule': typeof ReceptionScheduleRoute
  '/doctor/': typeof DoctorIndexRoute
  '/lab/': typeof LabIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/lab-requests': typeof DoctorLabRequestsRoute
  '/doctor/medical-records': typeof DoctorMedicalRecordsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/lab/completed': typeof LabCompletedRoute
  '/lab/in-progress': typeof LabInProgressRoute
  '/lab/pending': typeof LabPendingRoute
  '/lab/profile': typeof LabProfileRoute
  '/lab/search': typeof LabSearchRoute
  '/lab/upload': typeof LabUploadRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/lab-reports': typeof PatientLabReportsRoute
  '/patient/medical-records': typeof PatientMedicalRecordsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/request-appointment': typeof PatientRequestAppointmentRoute
  '/reception/billing': typeof ReceptionBillingRoute
  '/reception/patients': typeof ReceptionPatientsRoute
  '/reception/profile': typeof ReceptionProfileRoute
  '/reception/queue': typeof ReceptionQueueRoute
  '/reception/register': typeof ReceptionRegisterRoute
  '/reception/requests': typeof ReceptionRequestsRoute
  '/reception/schedule': typeof ReceptionScheduleRoute
  '/doctor': typeof DoctorIndexRoute
  '/lab': typeof LabIndexRoute
  '/patient': typeof PatientIndexRoute
  '/reception': typeof ReceptionIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/reception': typeof ReceptionRouteWithChildren
  '/register': typeof RegisterRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/lab-requests': typeof DoctorLabRequestsRoute
  '/doctor/medical-records': typeof DoctorMedicalRecordsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/lab/completed': typeof LabCompletedRoute
  '/lab/in-progress': typeof LabInProgressRoute
  '/lab/pending': typeof LabPendingRoute
  '/lab/profile': typeof LabProfileRoute
  '/lab/search': typeof LabSearchRoute
  '/lab/upload': typeof LabUploadRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/lab-reports': typeof PatientLabReportsRoute
  '/patient/medical-records': typeof PatientMedicalRecordsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/request-appointment': typeof PatientRequestAppointmentRoute
  '/reception/billing': typeof ReceptionBillingRoute
  '/reception/patients': typeof ReceptionPatientsRoute
  '/reception/profile': typeof ReceptionProfileRoute
  '/reception/queue': typeof ReceptionQueueRoute
  '/reception/register': typeof ReceptionRegisterRoute
  '/reception/requests': typeof ReceptionRequestsRoute
  '/reception/schedule': typeof ReceptionScheduleRoute
  '/doctor/': typeof DoctorIndexRoute
  '/lab/': typeof LabIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/lab'
    | '/login'
    | '/patient'
    | '/reception'
    | '/register'
    | '/doctor/appointments'
    | '/doctor/lab-requests'
    | '/doctor/medical-records'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/lab/completed'
    | '/lab/in-progress'
    | '/lab/pending'
    | '/lab/profile'
    | '/lab/search'
    | '/lab/upload'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/lab-reports'
    | '/patient/medical-records'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/request-appointment'
    | '/reception/billing'
    | '/reception/patients'
    | '/reception/profile'
    | '/reception/queue'
    | '/reception/register'
    | '/reception/requests'
    | '/reception/schedule'
    | '/doctor/'
    | '/lab/'
    | '/patient/'
    | '/reception/'
    | '/doctor/consultation/$id'
    | '/doctor/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/doctor/appointments'
    | '/doctor/lab-requests'
    | '/doctor/medical-records'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/lab/completed'
    | '/lab/in-progress'
    | '/lab/pending'
    | '/lab/profile'
    | '/lab/search'
    | '/lab/upload'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/lab-reports'
    | '/patient/medical-records'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/request-appointment'
    | '/reception/billing'
    | '/reception/patients'
    | '/reception/profile'
    | '/reception/queue'
    | '/reception/register'
    | '/reception/requests'
    | '/reception/schedule'
    | '/doctor'
    | '/lab'
    | '/patient'
    | '/reception'
    | '/doctor/consultation/$id'
    | '/doctor/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/lab'
    | '/login'
    | '/patient'
    | '/reception'
    | '/register'
    | '/doctor/appointments'
    | '/doctor/lab-requests'
    | '/doctor/medical-records'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/lab/completed'
    | '/lab/in-progress'
    | '/lab/pending'
    | '/lab/profile'
    | '/lab/search'
    | '/lab/upload'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/lab-reports'
    | '/patient/medical-records'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/request-appointment'
    | '/reception/billing'
    | '/reception/patients'
    | '/reception/profile'
    | '/reception/queue'
    | '/reception/register'
    | '/reception/requests'
    | '/reception/schedule'
    | '/doctor/'
    | '/lab/'
    | '/patient/'
    | '/reception/'
    | '/doctor/consultation/$id'
    | '/doctor/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  ReceptionRoute: typeof ReceptionRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/': {
      id: '/reception/'
      path: '/'
      fullPath: '/reception/'
      preLoaderRoute: typeof ReceptionIndexRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/reception/schedule': {
      id: '/reception/schedule'
      path: '/schedule'
      fullPath: '/reception/schedule'
      preLoaderRoute: typeof ReceptionScheduleRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/requests': {
      id: '/reception/requests'
      path: '/requests'
      fullPath: '/reception/requests'
      preLoaderRoute: typeof ReceptionRequestsRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/register': {
      id: '/reception/register'
      path: '/register'
      fullPath: '/reception/register'
      preLoaderRoute: typeof ReceptionRegisterRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/queue': {
      id: '/reception/queue'
      path: '/queue'
      fullPath: '/reception/queue'
      preLoaderRoute: typeof ReceptionQueueRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/profile': {
      id: '/reception/profile'
      path: '/profile'
      fullPath: '/reception/profile'
      preLoaderRoute: typeof ReceptionProfileRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/patients': {
      id: '/reception/patients'
      path: '/patients'
      fullPath: '/reception/patients'
      preLoaderRoute: typeof ReceptionPatientsRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/billing': {
      id: '/reception/billing'
      path: '/billing'
      fullPath: '/reception/billing'
      preLoaderRoute: typeof ReceptionBillingRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/patient/request-appointment': {
      id: '/patient/request-appointment'
      path: '/request-appointment'
      fullPath: '/patient/request-appointment'
      preLoaderRoute: typeof PatientRequestAppointmentRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medical-records': {
      id: '/patient/medical-records'
      path: '/medical-records'
      fullPath: '/patient/medical-records'
      preLoaderRoute: typeof PatientMedicalRecordsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/lab-reports': {
      id: '/patient/lab-reports'
      path: '/lab-reports'
      fullPath: '/patient/lab-reports'
      preLoaderRoute: typeof PatientLabReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/billing': {
      id: '/patient/billing'
      path: '/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof PatientBillingRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/lab/upload': {
      id: '/lab/upload'
      path: '/upload'
      fullPath: '/lab/upload'
      preLoaderRoute: typeof LabUploadRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/search': {
      id: '/lab/search'
      path: '/search'
      fullPath: '/lab/search'
      preLoaderRoute: typeof LabSearchRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/profile': {
      id: '/lab/profile'
      path: '/profile'
      fullPath: '/lab/profile'
      preLoaderRoute: typeof LabProfileRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/pending': {
      id: '/lab/pending'
      path: '/pending'
      fullPath: '/lab/pending'
      preLoaderRoute: typeof LabPendingRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/in-progress': {
      id: '/lab/in-progress'
      path: '/in-progress'
      fullPath: '/lab/in-progress'
      preLoaderRoute: typeof LabInProgressRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/completed': {
      id: '/lab/completed'
      path: '/completed'
      fullPath: '/lab/completed'
      preLoaderRoute: typeof LabCompletedRouteImport
      parentRoute: typeof LabRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/medical-records': {
      id: '/doctor/medical-records'
      path: '/medical-records'
      fullPath: '/doctor/medical-records'
      preLoaderRoute: typeof DoctorMedicalRecordsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/lab-requests': {
      id: '/doctor/lab-requests'
      path: '/lab-requests'
      fullPath: '/doctor/lab-requests'
      preLoaderRoute: typeof DoctorLabRequestsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof DoctorPatientsRoute
    }
    '/doctor/consultation/$id': {
      id: '/doctor/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/doctor/consultation/$id'
      preLoaderRoute: typeof DoctorConsultationIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorPatientsRouteChildren {
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
}

const DoctorPatientsRouteChildren: DoctorPatientsRouteChildren = {
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
}

const DoctorPatientsRouteWithChildren = DoctorPatientsRoute._addFileChildren(
  DoctorPatientsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorLabRequestsRoute: typeof DoctorLabRequestsRoute
  DoctorMedicalRecordsRoute: typeof DoctorMedicalRecordsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRouteWithChildren
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorConsultationIdRoute: typeof DoctorConsultationIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorLabRequestsRoute: DoctorLabRequestsRoute,
  DoctorMedicalRecordsRoute: DoctorMedicalRecordsRoute,
  DoctorPatientsRoute: DoctorPatientsRouteWithChildren,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorConsultationIdRoute: DoctorConsultationIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface LabRouteChildren {
  LabCompletedRoute: typeof LabCompletedRoute
  LabInProgressRoute: typeof LabInProgressRoute
  LabPendingRoute: typeof LabPendingRoute
  LabProfileRoute: typeof LabProfileRoute
  LabSearchRoute: typeof LabSearchRoute
  LabUploadRoute: typeof LabUploadRoute
  LabIndexRoute: typeof LabIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabCompletedRoute: LabCompletedRoute,
  LabInProgressRoute: LabInProgressRoute,
  LabPendingRoute: LabPendingRoute,
  LabProfileRoute: LabProfileRoute,
  LabSearchRoute: LabSearchRoute,
  LabUploadRoute: LabUploadRoute,
  LabIndexRoute: LabIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillingRoute: typeof PatientBillingRoute
  PatientLabReportsRoute: typeof PatientLabReportsRoute
  PatientMedicalRecordsRoute: typeof PatientMedicalRecordsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientRequestAppointmentRoute: typeof PatientRequestAppointmentRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillingRoute: PatientBillingRoute,
  PatientLabReportsRoute: PatientLabReportsRoute,
  PatientMedicalRecordsRoute: PatientMedicalRecordsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientRequestAppointmentRoute: PatientRequestAppointmentRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface ReceptionRouteChildren {
  ReceptionBillingRoute: typeof ReceptionBillingRoute
  ReceptionPatientsRoute: typeof ReceptionPatientsRoute
  ReceptionProfileRoute: typeof ReceptionProfileRoute
  ReceptionQueueRoute: typeof ReceptionQueueRoute
  ReceptionRegisterRoute: typeof ReceptionRegisterRoute
  ReceptionRequestsRoute: typeof ReceptionRequestsRoute
  ReceptionScheduleRoute: typeof ReceptionScheduleRoute
  ReceptionIndexRoute: typeof ReceptionIndexRoute
}

const ReceptionRouteChildren: ReceptionRouteChildren = {
  ReceptionBillingRoute: ReceptionBillingRoute,
  ReceptionPatientsRoute: ReceptionPatientsRoute,
  ReceptionProfileRoute: ReceptionProfileRoute,
  ReceptionQueueRoute: ReceptionQueueRoute,
  ReceptionRegisterRoute: ReceptionRegisterRoute,
  ReceptionRequestsRoute: ReceptionRequestsRoute,
  ReceptionScheduleRoute: ReceptionScheduleRoute,
  ReceptionIndexRoute: ReceptionIndexRoute,
}

const ReceptionRouteWithChildren = ReceptionRoute._addFileChildren(
  ReceptionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  ReceptionRoute: ReceptionRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
